# Generated by Django 5.0.6 on 2024-05-14 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 'Note'},
        ),
    ]
