# Generated by Django 5.0.6 on 2024-05-14 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members_app', '0002_alter_notes_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='date',
        ),
    ]
